### ISSUE TITLE
Assess whether the current Kafka client is sufficient

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-listener-hms#17]
the Kafka client send should be asynchronous.

But I notice that Egeria Kafka connector  uses a future to delay marking an operation as complete. Investigate whether this is required for the HMS listener.

**Comment by planetf1** [comment]
The kafka client send will already be asynchronous in many ways.

There is a fixed size buffer - if this fills, then the client will block for a fixed timeout (default 60s) before failing. Once in this situation this will likely cause hive transactions to fail, so we never want to get here...

The most likely cause is the broker being unavailable or slow -- but need to consider then how to handle? A backlog of calls could quickly occur. May need to mark the broker as 'bad' for a period before resuming, and ensure it's possible for an admin to know that  a bad situation occurred.

Alternatively, stick with kafka tuning ... and recommend values for the timeout and buffer size
